name: countries_explorer
description: "A modern Flutter mobile app for exploring countries with Clean Architecture and BLoC pattern."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5
  flutter_bloc: ^9.1.1
  dartz: ^0.10.1
  http: ^1.2.2
  shared_preferences: ^2.3.2
  get_it: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.3
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true